grpc:
  server:
    port: ${SERVER_PORT:9090}

spring:
  application:
    name: server
  r2dbc:
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
    url: r2dbc:${DATASOURCE_URL}
  data:
    jdbc:
      repositories:
        enabled: true
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    url: jdbc:${DATASOURCE_URL}
    user: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG