grpc:
  server:
    port: ${SERVER_PORT:9090}

spring:
  application:
    name: server
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/book_store
    driver-class-name: org.postgresql.Driver
