grpc:
  server:
    port: ${SERVER_PORT:9090}

spring:
  application:
    name: server
  r2dbc:
    username: postgres
    password: root
    url: r2dbc:postgresql://localhost:5432/book_store
  data:
    jdbc:
      repositories:
        enabled: true
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    url: jdbc:postgresql://localhost:5432/book_store
    user: postgres
    password: root
logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG